update ff bookmark script

diff --git a/firefox_bookmarks/gsbook b/firefox_bookmarks/gsbook
--- a/firefox_bookmarks/gsbook
+++ b/firefox_bookmarks/gsbook
@@ -1,12 +1,16 @@
+#!/bin/bash
+
 # t3.sh
 # Get Single BOOKmark
 set +x
 
-# AUTOMATE THIS !
-fin=/home/sk/.mozilla/firefox/z7do02ft.default-release/places.sqlite
+mkdir -p /tmp/ffbookmarks
+
+
 
 # single argument (tag)
 
+#-----------------------------------------------
 # make sure the app is available
 which sqlite3 >/dev/null
 if [ $? != 0 ]
@@ -15,7 +19,32 @@ then
 	exit 1
 fi
 
+#-----------------------------------------------
+# Fetch default profile folder of current user
+str=$(grep Default ~/.mozilla/firefox/profiles.ini)
 
+if [ $? != 0 ]
+then
+	echo "Error: unable to fetch current user's default profile"
+	exit 1
+fi
+# split string
+IFS=" ";read -a tab1 <<< "$str"
+echo "tab1=$tab1"
+IFS="=";read -a tab2 <<< "${tab1[0]}"
+echo "tab2=$tab2"
+folder=${tab2[1]}
+
+fin=/home/sk/.mozilla/firefox/$folder/places.sqlite
+echo "fin=$fin"
+if ! [ -e $fin ]
+then
+	echo "Error, file $fin does not exist"
+	exit 2
+fi
+
+
+# check if argument (tag) is given. If not, print the list of tags
 nb=$#
 if [ $nb == 0 ]
 then
@@ -34,6 +63,9 @@ then
 	exit 1
 fi
 
+IFS=$' \t\n'
+
+# 1 - Fetch the tag id in table moz_bookmarks
 echo ".open $fin" >temp_command
 echo "select id from moz_bookmarks where title='$1';" >>temp_command
 sqlite3 <temp_command >out1.txt
@@ -41,21 +73,22 @@ sqlite3 <temp_command >out1.txt
 index=$(cat out1.txt)
 #echo "index=$index"
 
+# 2 - Fetch the list of URL ids having that tag
 echo ".open $fin" >temp_command
 echo "select fk from moz_bookmarks where parent='$index';" >>temp_command
 sqlite3 <temp_command >out2.txt
 
-
+# 3 - Fetch the URLs from table moz_places using the indexes previously extracted
 echo ".open $fin" >temp_command
 for a in $(cat out2.txt);
 do
-#	echo $a
+#	echo "a=$a"
 	echo "select url from moz_places where id='$a';" >>temp_command
 done
 sqlite3 <temp_command >out3.txt
 
+# 4 - generate output html file
 nblinks=$(cat out3.txt|wc -l)
-# generate output html file
 fout=gsbook.html
 echo -e "<html>\n<head>\n<title>gsbook output</title>" >$fout
 echo -e "</head>\n<body>" >>$fout
@@ -68,7 +101,7 @@ done
 echo -e "</ul>\n</body>\n</html>" >>$fout
 
 # open output file in browser
-xdg-open $fout
+xdg-open $fout; echo ""
 
 
 
