wip

diff --git a/firefox_bookmarks/gsbook2 b/firefox_bookmarks/gsbook2
--- a/firefox_bookmarks/gsbook2
+++ b/firefox_bookmarks/gsbook2
@@ -1,7 +1,8 @@
 #!/bin/bash
 
-# t3.sh
-# Get Single BOOKmark
+# gsbook2
+
+# Get Single tag BOOKmark
 set +x
 
 mkdir -p /tmp/ffbookmarks
@@ -39,7 +40,7 @@ fin=/home/sk/.mozilla/firefox/$folder/places.sqlite
 echo "fin=$fin"
 if ! [ -e $fin ]
 then
-	echo "Error, file $fin does not exist"
+	echo "Error, Firefox sqlite file $fin does not exist"
 	exit 2
 fi
 
@@ -63,6 +64,7 @@ then
 	exit 1
 fi
 
+# restore IFS
 IFS=$' \t\n'
 
 # 1 - Fetch the tag id in table moz_bookmarks
@@ -70,57 +72,66 @@ echo ".open $fin" >temp_command
 echo "select id from moz_bookmarks where title='$1' AND type=2;" >>temp_command
 sqlite3 <temp_command >out1.txt
 
+nb1=$(echo out1.txt | wc -l)
+if ! [ $nb = 1 ]; then
+	echo "Error, file out1.txt has $nb1 lines"
+	exit 1
+fi
+
 rm out2.txt
 for index in $(cat out1.txt)
 do
 	echo "index=$index"
-	
+
 	# 2 - Fetch the list of URL ids having that tag
 	echo ".open $fin" >temp_command
 	echo "select fk from moz_bookmarks where parent='$index';" >>temp_command
 	sqlite3 <temp_command >>out2.txt
 done
 
+
 echo "out2 size=$(wc -l out2.txt)"
-fk=$(cat out2.txt)
 
-# get other tags with same URL
-echo ".open $fin" >temp_command
-echo "select parent from moz_bookmarks where fk='$fk';" >>temp_command
-sqlite3 <temp_command >out4.txt
-
-rm out5.txt
-for tag in $(cat out4.txt)
-do
-	echo "tag=$tag"
-	echo ".open $fin" >temp_command
-	echo "select title from moz_bookmarks where id='$tag' AND position>1;" >>temp_command
-#	echo "select title from moz_bookmarks where id='$tag';" >>temp_command
-	sqlite3 <temp_command >>out5.txt
-done
-
-rm out6.txt
-for tag in $(cat out5.txt)
-do
-	echo -n "$tag;">>out6.txt
-done
-echo "" >>out6.txt
-echo "" >>out6.txt
-
-#exit
-
-# 3 - Fetch the URLs from table moz_places using the indexes previously extracted
+#fk=$(cat out2.txt)
+rm out4.txt
 rm out3.txt
-echo ".open $fin" >temp_command
-for a in $(cat out2.txt);
-do
-#	echo "a=$a"
-	echo "select url from moz_places where id='$a';" >>temp_command
-done
-sqlite3 <temp_command >>out3.txt
-echo "" >>out3.txt
+rm out6.txt
 
-paste out3.txt out6.txt >out7.txt
+for fk in $(cat out2.txt)
+do
+# get other tags with same URL/fk
+	echo ".open $fin" >temp_command
+	echo "select parent from moz_bookmarks where fk='$fk';" >>temp_command
+	sqlite3 <temp_command >out4.txt
+
+
+	rm out5.txt
+	for tag in $(cat out4.txt)
+	do
+		echo "tag=$tag"
+		echo ".open $fin" >temp_command
+		echo "select title from moz_bookmarks where id='$tag' AND position>1;" >>temp_command
+	#	echo "select title from moz_bookmarks where id='$tag';" >>temp_command
+		sqlite3 <temp_command >>out5.txt
+	done
+
+#	rm out6.txt
+	for tag in $(cat out5.txt)
+	do
+		echo -n "$tag;">>out6.txt
+	done
+	echo "" >>out6.txt
+
+	echo ".open $fin" >temp_command
+	echo "select url from moz_places where id='$fk';" >>temp_command
+	sqlite3 <temp_command >>out3.txt
+	paste out3.txt out6.txt >out7.txt
+
+#	echo "read"
+#	read
+
+done
+
 
 # 4 - generate output html file
 nblinks=$(cat out3.txt|wc -l)
@@ -136,7 +147,7 @@ do
 #	echo "LINE0=${LINE[0]} LINE1=${LINE[1]}"
 	link=${LINE[0]}
 	tags=${LINE[1]}
-	echo -e "<li><a href='$link'>$link</a> tags:$tags</li>\n" >>$fout
+	echo -e "<li><a href='$link' target='_blank'>$link</a> tags:$tags</li>\n" >>$fout
 done< out7.txt
 
 echo -e "</ul>\n</body>\n</html>" >>$fout
